/* =========================
   QUESTIONS CONFIG
========================= */
const questions = [
  {
    text: "What is this website for?",
    options: [
      "Business",
      "Portfolio",
      "Startup",
      "Event",
      "Blog",
      "Online Store",
      "Personal"
    ]
  },
  {
    text: "What is the topic or industry?",
    options: [
      "Technology",
      "Gaming",
      "Education",
      "Fashion",
      "Fitness",
      "Food",
      "Finance",
      "Other"
    ],
    hasOther: true
  },
  {
    text: "How should it feel?",
    options: [
      "Minimal",
      "Bold",
      "Futuristic",
      "Elegant",
      "Playful",
      "Professional"
    ]
  },
  {
    text: "Who is this website for?",
    options: [
      "Kids",
      "Teens",
      "Professionals",
      "Everyone"
    ]
  },
  {
    text: "What is the main goal of this website?",
    textOnly: true
  }
];

let currentStep = 0;
const answers = {};

/* =========================
   ELEMENTS
========================= */
const questionEl = document.getElementById("question");
const optionsEl = document.getElementById("options");
const textInput = document.getElementById("textInput");
const nextBtn = document.getElementById("nextBtn");
const progressBar = document.getElementById("progressBar");

/* =========================
   RENDER QUESTIONS
========================= */
function renderStep() {
  const step = questions[currentStep];

  questionEl.textContent = step.text;
  optionsEl.innerHTML = "";
  textInput.value = "";
  textInput.classList.add("hidden");
  nextBtn.classList.add("hidden");

  progressBar.style.width =
    ((currentStep + 1) / questions.length) * 100 + "%";

  if (step.textOnly) {
    textInput.classList.remove("hidden");
    nextBtn.classList.remove("hidden");
    return;
  }

  step.options.forEach(option => {
    const div = document.createElement("div");
    div.className = "option";
    div.textContent = option;

    div.onclick = () => {
      if (option === "Other" && step.hasOther) {
        optionsEl.innerHTML = "";
        textInput.classList.remove("hidden");
        nextBtn.classList.remove("hidden");
        textInput.focus();
      } else {
        answers[step.text] = option;
        goNext();
      }
    };

    optionsEl.appendChild(div);
  });
}

function goNext() {
  currentStep++;
  if (currentStep < questions.length) {
    renderStep();
  } else {
    generateWebsite();
  }
}

nextBtn.onclick = () => {
  if (!textInput.value.trim()) return;
  answers[questions[currentStep].text] = textInput.value.trim();
  goNext();
};

/* =========================
   FAKE AI GENERATION
========================= */
function generateWebsite() {
  questionEl.textContent = "Creating your website…";
  optionsEl.innerHTML = "";
  textInput.classList.add("hidden");
  nextBtn.classList.add("hidden");
  progressBar.style.width = "100%";

  const messages = [
    "Designing layout…",
    "Choosing colors…",
    "Adding sections…",
    "Applying animations…",
    "Finalizing website…"
  ];

  let i = 0;
  const interval = setInterval(() => {
    questionEl.textContent = messages[i];
    i++;
    if (i === messages.length) {
      clearInterval(interval);
      setTimeout(showResult, 600);
    }
  }, 600);
}

/* =========================
   GENERATED WEBSITE
========================= */
function showResult() {
  document.getElementById("card").innerHTML = `
    <nav class="site-nav">
      <div class="logo">SiteForge</div>
      <div class="nav-links">
        <span>Home</span>
        <span>Features</span>
        <span>Contact</span>
      </div>
    </nav>

    <section class="hero">
      <h1>Your Website. Built by AI.</h1>
      <p>Designed from your answers. Ready to customize.</p>
      <button class="primary" onclick="openPanel()">Edit Design</button>
    </section>

    <section class="features">
      <div class="feature-card">⚡ Fast Setup</div>
      <div class="feature-card">🎨 Smart Design</div>
      <div class="feature-card">📱 Mobile Ready</div>
    </section>

    <footer class="footer">
      Generated by SiteForge AI
    </footer>

    <div id="panel" class="panel hidden">
      <h2>Design Settings</h2>

      <div class="panel-section">
        <h3>Theme</h3>
        <button onclick="setTheme('soft')">Soft</button>
        <button onclick="setTheme('dark')">Dark</button>
        <button onclick="setTheme('neon')">Neon</button>
      </div>

      <div class="panel-section">
        <h3>Animations</h3>
        <button onclick="setAnim('calm')">Calm</button>
        <button onclick="setAnim('energetic')">Energetic</button>
        <button onclick="setAnim('none')">None</button>
      </div>

      <button class="close" onclick="closePanel()">Close</button>
    </div>
  `;
}

/* =========================
   PANEL CONTROLS
========================= */
function openPanel() {
  document.getElementById("panel").classList.remove("hidden");
}

function closePanel() {
  document.getElementById("panel").classList.add("hidden");
}

/* =========================
   THEMES
========================= */
function setTheme(type) {
  const body = document.body;

  body.classList.remove("theme-soft", "theme-dark", "theme-neon");

  if (type === "soft") body.classList.add("theme-soft");
  if (type === "dark") body.classList.add("theme-dark");
  if (type === "neon") body.classList.add("theme-neon");
}

/* =========================
   ANIMATIONS
========================= */
function setAnim(type) {
  const hero = document.querySelector(".hero");

  hero.classList.remove("anim-calm", "anim-energetic");

  if (type === "calm") hero.classList.add("anim-calm");
  if (type === "energetic") hero.classList.add("anim-energetic");
}

/* =========================
   INIT
========================= */
renderStep();
